/*
 * generated by Xtext 2.10.0
 */
package ru.agentlab.powerloom.dsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class PowerloomDslRuntimeModule extends AbstractPowerloomDslRuntimeModule {
}
