/*
 * generated by Xtext 2.10.0
 */
package ru.agentlab.powerloom.dsl.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class PowerloomDslUiModule extends AbstractPowerloomDslUiModule {
}
